name: tabulate
description: A simple library to generate text-based table for console-printing.
version: 0.0.1
# homepage: https://www.example.com
author: BLeAmz <bleamz@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
